name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build-application-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Styleguide
        run: |
          pip install wemake-python-styleguide

      - name: Check Code Style
        run: |
          wemake-python-styleguide --reporter=github-pr-review
      - name: Run tests
        run: |
          python -m unittest discover -s tests
  deploy-on-ecs:
    runs-on: ubuntu-latest
    needs: build-application-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4




